"""Data structures produced by the enrichment pipeline.

An :class:`EnrichedSalon` is the fully cleaned, deduplicated, AI-annotated
record — the shape that is written to the committed seed and loaded into the
database.
"""

from pydantic import BaseModel, Field


class EnrichedSalon(BaseModel):
    """A salon after normalization, dedup, summarization, and embedding."""

    source: str
    source_id: str
    name: str
    address: str
    district: str
    latitude: float | None = None
    longitude: float | None = None
    phone: str | None = None
    website: str | None = None
    price_range: str | None = None
    rating: float | None = None
    review_count: int | None = None
    raw_services_text: str | None = None
    review_summary: str | None = None
    # Canonical service slugs from the taxonomy.
    service_slugs: list[str] = Field(default_factory=list)
    # Search embedding; ``None`` until generated by an embedding-capable run.
    embedding: list[float] | None = None
    # Provenance of records merged into this canonical one during dedup.
    merged_source_ids: list[str] = Field(default_factory=list)
